spring:
  application:
    name: task-service

server:
  port: ${TASK_SERVICE_PORT:9083}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
