spring:
  application:
    name: project-service

server:
  port: ${PROJECT_SERVICE_PORT:9082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
